In [ ]:
#NO 1
Nama  : Yulfika Kaitana
Kelas : TI22F

In [1]:
data_nilai = [
    {
        "student_number" : "101",
        "Name" : "Andri",
        "Subject" : "Programming Basic",
        "Grade" : 80
    },
    {
        "student_number" : "102",
        "Name" : "Budi",
        "Subject" : "Programming Basic",
        "Grade" : 90
    },
    {
        "student_number" : "103",
        "Name" : "Cika",
        "Subject" : "Programming Basic",
        "Grade" : 100
    },
    {
        "student_number" : "104",
        "Name" : "Dedi",
        "Subject" : "Programming Basic",
        "Grade" : 100
    },
    {
        "student_number" : "105",
        "Name" : "Eka",
        "Subject" : "Programming Basic",
        "Grade" : 50
    },
    {
        "student_number" : "106",
        "Name" : "Feri",
        "Subject" : "Programming Basic",
        "Grade" : 40
    },
    {
        "student_number" : "107",
        "Name" : "Galih",
        "Subject" : "Programming Basic",
        "Grade" : 70
    },
    {
        "student_number" : "108",
        "Name" : "Huda",
        "Subject" : "Programming Basic",
        "Grade" : 70
    },
    {
        "student_number" : "109",
        "Name" : "Intan",
        "Subject" : "Programming Basic",
        "Grade" : 60
    },
    {
        "student_number" : "101",
        "Name" : "Andri",
        "Subject" : "Web Programming",
        "Grade" : 70
    },
    {
        "student_number" : "102",
        "Name" : "Budi",
        "Subject" : "Web Programming",
        "Grade" : 80
    },
    {
        "student_number" : "103",
        "Name" : "Cika",
        "Subject" : "Web Programming",
        "Grade" : 80
    },
    {
        "student_number" : "104",
        "Name" : "Dedi",
        "Subject" : "Web Programming",
        "Grade" : 90
    },
    {
        "student_number" : "105",
        "Name" : "Eka",
        "Subject" : "Web Programming",
        "Grade" : 90
    },
    {
        "student_number" : "106",
        "Name" : "Feri",
        "Subject" : "Web Programming",
        "Grade" : 60
    },
    {
        "student_number" : "107",
        "Name" : "Galih",
        "Subject" : "Web Programming",
        "Grade" : 95
    },
    {
        "student_number" : "108",
        "Name" : "Huda",
        "Subject" : "Web Programming",
        "Grade" : 85
    },
    {
        "student_number" : "109",
        "Name" : "Intan",
        "Subject" : "Web Programming",
        "Grade" : 90
    },
]

In [2]:
def nilaiLebih80(data_nilai):
    result = []

    for item in data_nilai:
        if item.get("Grade") > 80:
            result.append(item)

    return result

In [8]:
def printData(data_nilai):
    for item in data_nilai:
        print("===============================")
        print("Student Number : ", item.get("student_number"))
        print("Nama : ", item.get("Name"))
        print("Subjects : ", item.get("Subject"))
        print("Grades : ", item.get("Grade"))
        print("===============================")
        print("\n")

In [9]:
print("Data dengan nilai lebih dari 80\n")
printData(nilaiLebih80(data_nilai))

Data dengan nilai lebih dari 80

===============================
Student Number :  102
Nama :  Budi
Subjects :  Programming Basic
Grades :  90
===============================


===============================
Student Number :  103
Nama :  Cika
Subjects :  Programming Basic
Grades :  100
===============================


===============================
Student Number :  104
Nama :  Dedi
Subjects :  Programming Basic
Grades :  100
===============================


===============================
Student Number :  104
Nama :  Dedi
Subjects :  Web Programming
Grades :  90
===============================


===============================
Student Number :  105
Nama :  Eka
Subjects :  Web Programming
Grades :  90
===============================


===============================
Student Number :  107
Nama :  Galih
Subjects :  Web Programming
Grades :  95
===============================


===============================
Student Number :  108
Nama :  Huda
Subjects :  Web Programming
Grades :  85
===============================


===============================
Student Number :  109
Nama :  Intan
Subjects :  Web Programming
Grades :  90
===============================